"""Turn a diff result into something a freezer understands."""

from __future__ import annotations

from collections.abc import Sequence

_HEADER = (
    "# Generated by hookfix. https://github.com/sqmyou/hookfix\n"
    "#\n"
    "# These modules were imported at runtime by the traced program but are not\n"
    "# reachable from a static scan of the source, so PyInstaller would omit them.\n"
    "# Review the list before committing: it reflects one execution of the program.\n"
)


def hook_targets(modules: Sequence[str]) -> list[str]:
    """Top-level module names a hook must be keyed to, in first-seen order.

    PyInstaller consults ``hook-<name>.py`` only while it is processing the
    module ``<name>``. The modules worth hiding are submodules, so the hook has
    to be keyed to the top-level package that owns them: ``reporters`` for
    ``reporters.json_reporter``.
    """
    targets: list[str] = []
    for name in modules:
        top = name.split(".")[0]
        if top not in targets:
            targets.append(top)
    return targets


def render_hook_file(modules: Sequence[str], *, module_name: str) -> str:
    """Render a PyInstaller hook file (``hook-<module_name>.py``).

    ``module_name`` must be a module PyInstaller actually processes, otherwise
    the file is never read. In particular it cannot be the entry script:
    PyInstaller knows the entry script as ``__main__``, so a hook named after
    the script file never fires. Use :func:`hook_targets` to pick names.
    """
    body = "\n".join(f"    {name!r}," for name in modules) or "    # (none)"
    return (
        f"{_HEADER}"
        f"# hook-{module_name}.py\n"
        f"\n"
        f"hiddenimports = [\n"
        f"{body}\n"
        f"]\n"
    )


def render_spec_patch(modules: Sequence[str]) -> str:
    """Render the ``hiddenimports`` line to paste into an existing ``.spec`` file.

    PyInstaller's generated spec files already contain a ``hiddenimports = []``
    entry; this is the drop-in replacement for it.
    """
    body = "\n".join(f"    {name!r}," for name in modules) or "    # (none)"
    return f"hiddenimports = [\n{body}\n]\n"
