"""Turn a diff result into something a freezer understands."""

from __future__ import annotations

from collections.abc import Sequence

_HEADER = (
    "# Generated by hookfix. https://github.com/sqmyou/hookfix\n"
    "#\n"
    "# These modules were imported at runtime by the traced program but are not\n"
    "# reachable from a static scan of the source, so PyInstaller would omit them.\n"
    "# Review the list before committing: it reflects one execution of the program.\n"
)


def render_hook_file(modules: Sequence[str], *, module_name: str | None = None) -> str:
    """Render a PyInstaller hook file (``hook-<name>.py``).

    A hook is the reusable form of ``--hidden-import``: it applies automatically
    whenever the named module is imported, including inside a frozen build.
    """
    title = module_name or "your_app"
    body = "\n".join(f"    {name!r}," for name in modules) or "    # (none)"
    return (
        f"{_HEADER}"
        f"# hook-{title}.py\n"
        f"\n"
        f"hiddenimports = [\n"
        f"{body}\n"
        f"]\n"
    )


def render_spec_patch(modules: Sequence[str]) -> str:
    """Render the ``hiddenimports`` line to paste into an existing ``.spec`` file.

    PyInstaller's generated spec files already contain a ``hiddenimports = []``
    entry; this is the drop-in replacement for it.
    """
    body = "\n".join(f"    {name!r}," for name in modules) or "    # (none)"
    return f"hiddenimports = [\n{body}\n]\n"
